# =====温馨提示=====
# 此文件编码格式为UTF-8，请注意冒号后面有个空格，如遇到此文件出错，删除此文件即可重置。可以使用颜色代码：https://tieba.baidu.com/p/5010745847?red_tag=3368126674。
# 全部都是英文符号!
# 作者：Wickham阿华

# =====系统设置=====
启动MySQL: true
# 目前不能启动非MySQL模式

# =====MySQL设置=====
用户名: root
密码: 16816816
MySQL服务器地址: localhost
MySQL服务器端口: 3306
数据库名字: mc