name: WLogin
main: wickham.main.WLogin
load: STARTUP
authors: [Wickham, HomeRich]
website: https://github.com/WickhamWei/WLogin
version: 1.0
api-version: 1.14
commands:
   login:
      description: 登录
      usage: /login 你的密码
   register:
      description: 注册
      usage: /register 你的密码 重复一遍你的密码
   unlogin:
      description: 退出登录
      usage: /unlogin playerName
   changepassword:
      description: 修改密码
      usage: /changepassword 你的密码 重复一遍你的密码 或者 /changepassword 玩家名字 密码 重复一遍密码
   logindata:
      description: 查询登录数据
      usage: /logindata